ExamProject.UI/Controllers/CategoryController.cs
using Business.Abstract;
using DataAccess.Concrete;
using Entities.Concrete;
using ExamProject.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace ExamProject.UI.Controllers
{

    public class CategoryController : Controller
    {

        private readonly ISubCategoryService _subCategoryService;
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService,ISubCategoryService subCategoryService)
        {
            _categoryService = categoryService;
            _subCategoryService = subCategoryService;
        }
        [Authorize(Roles = "Admin,Member")]
        public IActionResult Index()
        {
            return View(_categoryService.GetAll());
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            CategoriesViewModel model = new CategoriesViewModel();
            model.Category = _categoryService.GetAll().SingleOrDefault(x=>x.CategoryId==id);
            model.SubCategory = _subCategoryService.GetByCategories().Where(x=>x.CategoryId==id).ToList();
            return View(model);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.Add(category);
                return RedirectToAction("Index");
            }

            return View(category);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, int _) 
        {
            var result = _categoryService.GetAll().SingleOrDefault(q => q.CategoryId == id);
            return View(result);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Category category)
        {
            _categoryService.Update(category, id);
            return RedirectToAction("Index");

        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, int _)
        {
            var result = _categoryService.GetAll().SingleOrDefault(q => q.CategoryId == id);
            return View(result);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {

            _categoryService.Delete(id);
            return RedirectToAction("Index");

        }

    }
}

ExamProject.UI/Controllers/ExamController.cs
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamProject.UI.Controllers
{
     public class ExamController : Controller
    {
        // GET: ExamController

        private readonly IExamService _examService;

        public ExamController(IExamService examService)
        {
            _examService = examService;
        }
        [Authorize(Roles = "Admin,Member")]
        public IActionResult Index()
        {
            return View(_examService.GetByCategories());
        }

        [Authorize(Roles = "Admin,Member")]
        public IActionResult GetQuestionsByExam(int id)
        {
            return View(_examService.GetQuestionsByExam(id));
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            Exam exam = _examService.GetByCategories().SingleOrDefault(x=>x.ExamId==id);

            return View(exam);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Exam exam)
        {
            if (ModelState.IsValid)
            {
                _examService.Add(exam);
                return RedirectToAction("Index");
            }

            return View(exam);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id,int _)
        {
            var result = _examService.GetAll().SingleOrDefault(q => q.ExamId == id);
            return View(result);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Exam exam)
        {

            _examService.Update(exam, id);
            return RedirectToAction("Index");


        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, int _)
        {
            var result = _examService.GetAll().SingleOrDefault(q => q.ExamId == id);
            return View(result);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {

            _examService.Delete(id);
            return RedirectToAction("Index");

        }
    }
}

ExamProject.UI/Controllers/QuestionController.cs
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamProject.UI.Controllers
{

    public class QuestionController : Controller
    {
        private readonly IQuestionService _questionService;
        private static int _score;
        public QuestionController(IQuestionService questionService)
        {
            _questionService = questionService;
            int score = 0;
            _score = score;
        }
        [Authorize(Roles = "Admin,Member")]
        public IActionResult Index()
        {
          var result= _questionService.GetAllQuestionWithQuestionAnswers();
            return View(result);
        }

        [Authorize(Roles = "Admin,Member")]
        public IActionResult GetQuestionsBySubCategory(int id)
        {
            return View(_questionService.GetQuestionsBySubCategory(id));
        }
        [Authorize(Roles = "Admin,Member,")]
        public IActionResult GetQuestionsByExam(int id)
        {
            return View(_questionService.GetQuestionsByExam(id));
        }


        public IActionResult GetQuestionsWithAnswers(int id,string answer)
        {
            var questionOld = _questionService.GetById(id);
            if (answer != null && questionOld.CorrectAnswer == answer)
            {
                _score += 1;
            }

            var questionLast = _questionService.GetAll().OrderByDescending(q => q.QuestionId).Take(1).SingleOrDefault();

            if (questionLast.QuestionId == id)
            {
                questionOld = _questionService.GetById(id);
                ViewData["lastquestion"] = id;
                return View(questionOld);
            }

            var question = _questionService.GetAllQuestionWithQuestionAnswers().Where(x=>x.ExamId == 1)
                .FirstOrDefault(x=>x.QuestionId > id);

             return View(question);
        }


        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            Question question = _questionService.GetAllQuestionWithQuestionAnswers().SingleOrDefault(x=>x.QuestionId==id);

            return View(question);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                _questionService.Add(question);
                return RedirectToAction("Index");
            }

            return View(question);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, int _)
        {
            var result = _questionService.GetAllQuestionWithQuestionAnswers().SingleOrDefault(q => q.QuestionId == id);
            return View(result);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Question question)
        {

            _questionService.Update(question, id);
            return RedirectToAction("Index");


        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id,int _)
        {
           var result= _questionService.GetAllQuestionWithQuestionAnswers().SingleOrDefault(q=>q.QuestionId==id);
            return View(result);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {

            _questionService.Delete(id);
            return RedirectToAction("Index");

        }
    }
    }

ExamProject.UI/Controllers/SubCategoryController.cs
using Business.Abstract;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;


namespace ExamProject.UI.Controllers
{
    public class SubCategoryController : Controller
    {

        private readonly ISubCategoryService _subCategoryService;

        public SubCategoryController(ISubCategoryService subCategoryService)
        {
            _subCategoryService = subCategoryService;
        }

        [Authorize(Roles = "Admin,Member")]
        public ActionResult Index()
        {
            return View(_subCategoryService.GetByCategories());
        }

        [Authorize(Roles = "Admin,Member")]
        public IActionResult GetQuestionsBySubCategory(int id)
        {
            return View(_subCategoryService.GetQuestionsBySubCategory(id));
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            SubCategory subCategory = _subCategoryService.GetByCategories().SingleOrDefault(x=>x.SubCategoryId==id);

            return View(subCategory);


        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SubCategory subCategory)
        {

            if (ModelState.IsValid)
            {
                _subCategoryService.Add(subCategory);
                return RedirectToAction("Index");
            }

            return View(subCategory);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id,int _)
        {
            var result = _subCategoryService.GetByCategories().SingleOrDefault(q => q.SubCategoryId == id);
            return View(result);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, SubCategory subCategory)
        {
            _subCategoryService.Update(subCategory, id);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var result = _subCategoryService.GetByCategories().SingleOrDefault(q => q.SubCategoryId == id);
            return View(result);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, SubCategory subCategory)
        {
            _subCategoryService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ExamProject.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamProject.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <main class="container-fluid bg-light p-0">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <img src="https://img.icons8.com/external-justicon-lineal-color-justicon/38/000000/external-exam-back-to-school-justicon-lineal-color-justicon.png" />


            <span class="navbar-brand" style="color:white;font-family:'Arial Rounded MT';margin-left:8px" href="/Home/Index"><b> E-Sınav </b></span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">

                        <a class="btn btn-outline-light ml-2" style="font-family: 'Arial Rounded MT'; " href="/Home/Index"><b>Anasayfa</b></a>
                    </li>

                    <li class="nav-item">

                        <a class="btn btn-outline-light ml-2" style="font-family: 'Arial Rounded MT' ; " href="/Category/Index"><b>Dersler</b></a>
                    </li>
                    <li class="nav-item">

                        <a class="btn btn-outline-light ml-2" style="font-family: 'Arial Rounded MT';   " href="/SubCategory/Index"><b>Konular</b></a>
                    </li>
                    <li class="nav-item">

                        <a class="btn btn-outline-light ml-2" style="font-family: 'Arial Rounded MT';  " href="/Exam/Index"><b>Sınavlar</b></a>
                    </li>
                    <li class="nav-item">

                        <a class="btn btn-outline-light ml-2" style="font-family: 'Arial Rounded MT';   " href="/Question/Index"><b>Sorular</b></a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">

                    <a class="btn btn-outline-info ml-2" style="font-family: 'Arial Rounded MT';  " asp-action="Login" asp-controller="Home"><b>Login</b></a>

                    <a class="btn btn-outline-info ml-2" style="font-family: 'Arial Rounded MT'; " asp-action="Register" asp-controller="Home"><b>Sign Up</b></a>

                </form>

            </div>
        </nav>

        @RenderBody()
    </main>




















    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamProject.UI</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Dersler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SubCategory" asp-action="Index">Konular</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Exam" asp-action="Index">Sınavlar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="Index">Sorular</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-2">
                @RenderBody()
            </main>*@
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExamProject.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)



</body>
</html>